# Welcome to Jekyll!
#

# Site settings
title: vetrnry
description: |
  Veterinary consultants
owner: vetrnry
first_published: 2016 # if migrating another site, the year of your first publish
email: contact@vetrnry.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vetrnry.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/vetrnry
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: contact@vetrnry.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit: https://reddit.com/r/vetrnry
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
